# Generated by Django 3.2.4 on 2021-07-03 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('autor', models.CharField(max_length=20, verbose_name='Autor')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='idcategoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=50, verbose_name='NombreCategoria'),
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.AddField(
            model_name='libro',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
